int main() { 
    try  { 
       throw 10; 
    } 
    catch (char *e)  { cout << "Caught " << e; } 
    catch (...)  { cout << "Default Exception\n"; } 
    return 0; 
}
